repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-toml
    - id: check-json
    - id: debug-statements
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.18.2
    hooks:
    - id: stylua-system
