---
- name: Set up local machine
    host: localhost
      connection: local
      roles:
      - role: ripgrep
         tags:
          - ripgrep
  - name: Test Shell
    hosts: all
    tasks:
      - name: List files and folders
        ansible.builtin.command: 'ls -l'
        register: command_output

