- name: Set up local machine
  hosts: local
  become: yes
  become_user: root
  connection: local
  roles:
    - pre-tasks
    - tools
    - rust
    - golang
    - nodejs
    - neovim
    - post-tasks
