- name: Set up local machine
  hosts: local
  connection: local
  gather_facts: yes

  tasks:
    - block:
        - name: Include RedHat roles
          include_tasks: roles/fedora-tasks/tasks/main.yml
      become: yes
      become_user: root
      become_method: sudo
      when: ansible_os_family == 'RedHat'

    - block:
        - name: Include Ubuntu roles
          include_tasks: roles/ubuntu-tasks/tasks/main.yml
      become: yes
      become_user: root
      become_method: sudo
      when: ansible_os_family == 'Debian'

    - block:
        - name: Include MacOS roles
          include_tasks: roles/mac-tasks/tasks/main.yml
      when: ansible_os_family == 'Darwin'

