---
#- name: Set up local machine
    #host: localhost
      #connection: local
      #roles:
      #- role: ripgrep
        #        tags:
#          - ripgrep
  - name: Test
    ansible.builtin.command: 'ls -l *'
    register: command_output

