- name: Download familiar tools
  ansible.builtin.package:
    name:
      - cmake
      - pass
      - make
      - gcc
      - gcc-c++
      - sqlite
      - glibc-devel
      - kernel-devel
      - automake
      - clang
      - unzip
      - wget
      - curl
      - python3-pip
      - ShellCheck
      - stow
      - git
      - gh
      - libicu
      - perf
      - iputils
      - uv
    state: latest
