- name: Rust tasks
  block:
  - name: Install rust toolchain installer
    ansible.builtin.package:
      name:
        - rustup
      state: latest

  - name: Install stable release
    ansible.builtin.shell: rustup default stable

  - name: Install neovim tools
    community.general.cargo:
      name:
        - ripgrep
        - fd-find
      state: latest

  - name: Install starhip
    community.general.cargo:
      name:
        - starship
      state: latest

  become: true
  become_user: "{{ current_user }}"
