- name: Install rust toolchain installer
  ansible.builtin.package:
    name:
      - rustup
    state: latest


- name: Rust tasks for user
  block:
  - name: Install stable release
    ansible.builtin.shell: rustup default stable

  - name: Install nvim tools with cargo
    community.general.cargo:
      name:
        - ripgrep
        - fd-find
      state: latest

  - name: Install starship
    community.general.cargo:
      name:
        - starship
      state: latest

  become: true
  become_user: "{{ current_user }}"
