- name: Update cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install tools
  ansible.builtin.apt:
    pkg:
      - ripgrep

- name: Remove obsolete packages
  ansible.builtin.apt:
    autoremove: yes

- name: So fresh and so clean clean
  ansible.builtin.apt:
    autoclean: yes
