- name: Check if curl is installed
  shell: curl --version
  register: curl_exists 
  ignore_errors: yes
 
- name: Download curl
  when: curl_exists is failed
  ansible.builtin.apt:
    name: curl
    state: latest

- name: Download build-essential
  ansible.builtin.apt:
    name: build-essential
    state: latest
