- name: Update cache
  ansible.builtin.package:
    update_cache: yes

- name: Install community.general collection
  community.general.ansible_galaxy_install:
    type: collection
    name: community.general
